### ISSUE TITLE
似乎对于超过39999star的项目处理有异常

### ISSUE THREAD

**Issue by ahjsrhj** [pingao777/github-gazer#4]
如图，39999之后的部分有bug
![image](https://user-images.githubusercontent.com/8666955/55215468-deb9b400-5234-11e9-8c31-ef5fb42415d3.png)

链接如下：
[https://pingao777.github.io/github-gazer/?q=996icu/996.ICU](https://pingao777.github.io/github-gazer/?q=996icu/996.ICU)

**Comment by naosense** [comment]
哈哈看来这两天都在看996icu。这个不是bug，是github有限制，只让获取前40000个star

**Comment by ahjsrhj** [comment]
搜噶，
现象级项目，好奇star增长情况～
